### ISSUE TITLE
[여행메이트페이지2]

### ISSUE THREAD

**Issue by zhenying2** [zhenying2/IPS_tripstargram#2]
- [x] 검색창 기본 레이아웃 설정(옆에 돋보기도 넣었음)
- [x] 글쓰기 버튼 추가
- [x] 여행메이트 페이지 하위 메뉴 추가
- [x] 각 메뉴에 마우스 hover시, 드롭다운 메뉴바 설정 추가
- [x] db-> 메이트 페이지에 보일 수 있도록 구현
- [x] 글쓰기 버튼 클릭시, 생기는 글쓰기 레이아웃
- [x] 쓴 글 -> db로 이동 (로그인해야 글쓸수 있게 해놨는데, ,,,, 로그인 파일이랑 연동을 아직 못했습니다.)
- [x] 메인페이지에서의 정렬
- [x] 쓴 글 로그인한 id연결만 하면 바로 뜰거에요,, 근데 이거 연결을 아직 못함,, key값 author.....

파일명: question_list.html

@kyungminlee-12 @zhenying2 @pysdsc @yena45

**Comment by zhenying2** [comment]
검색창에 검색어 넣은 후 -> 연관 검색글 뜨는 검색엔진 부분은 제가 맡아 진행하겠습니다.
(이번주 평일에 관련 공부 수행 후 주말에 만든 코드 공유하겠습니다.)

**Comment by kyungminlee-12** [comment]
이 페이지를 db와 연동하는 기능은 제가 구현하고 있겠습니다. 저장된 글을 이 페이지로 끌고 오는 기능은 구현한 상태입니다.  -경민-

**Comment by zhenying2** [comment]
@kyungminlee-12 저도 그렇게 생각했어요! 글작성 레이아웃 완성된후에 글->db는 연동시키면 될 것 같아요 :)

**Comment by zhenying2** [comment]
@kyungminlee-12 경민아 카톡 확인해줘!!!!!!!!!!!!!!!!!!!!
경민이가 admin-> 글가져오는건 한거야????
이거 장고를 이해하고 코딩하기엔 시간이 없어서, 클론코딩 목적으로 일단 완성시키려하는데,
어디서 멈춰야될지를 모르겠어서 내가 이 페이지 다 만들게 될 것 같은데,,,,
?!?!?!?!

**Comment by zhenying2** [comment]
finish
