### ISSUE TITLE
[글쓰기페이지1]

### ISSUE THREAD

**Issue by yena45** [zhenying2/IPS_tripstargram#3]
자유로운글쓰기페이지1_본 페이지 파일명: freewritepage.html
일반 글쓰기 페이지: 1.html
초대 글쓰기 페이지: invitewritepage

수행한것: 전체적인 레이아웃

앞으로 수행해야 할 것

- [ ] 초대 글쓰기 지도 api추가하기

- [ ] 자유로운 글쓰기 페이지 - 공지글은 맨 위 상단에 고정

- [ ] 일반글쓰기 페이지 & 초대 글쓰기 페이지 - 이모티콘 텍스트필드에 나오게하기

- [ ] 드라이브 연결하기

**Comment by zhenying2** [comment]
예나~~~~ 카톡 확인 늦을까봐 여기에도 남겨요~~
일반글쓰기 페이지 소스코드 공유해줘요!!!!!
이 템플릿으로 여행메이트 게시판 글쓰기 db연결시켜서 저장하는 작업 하려고 합니다~~ :)

**Comment by zhenying2** [comment]
전체적 구현 완료
finish
